---
- name: Install Elasticsearch
  hosts: elastic
  roles: 
  - elastic
  tags: elastic

- name: Install Kibana
  hosts: kibana
  roles: 
  - kibana
  tags: kibana

- name: Install Filebeat
  hosts: all
  roles: 
  - filebeat
  tags: filebeat
